[CROC-46] fix screens size bindings and refactor
xylini/mi-czw-1250-ciroc pull request #32
Opened 2019-05-24 08:59 UTC by tadeq

2019-05-24 14:43 UTC, xylini requested changes
W main wywalić komentarze

2019-05-24 14:52 UTC, xylini commented on src/main/java/pl/edu/agh/timekeeper/Main.java
> +        primaryStage.setTitle("TimeKeeper");
optowałbym jednak za nazwą "Time Keeper" bo wg mnie jest bardziej przyjazna dla użytkownika. Niby kwestia gustu ale w tej chwili nie pamiętam żadnej appki która składała się z dwóch wyrazów i była pisana CamelCase'm

2019-05-24 15:01 UTC, xylini commented on src/main/java/pl/edu/agh/timekeeper/controller/AddRestrictionController.java
>              System.out.println("Restriction with given name already exists");
tutaj było: 
// TODO: show message "Restriction with given name already exists"
i jest usunięte a nie widzę nigdzie taska żeby to zrobić, chyba że istnieje task w którym ma to być zrobione lub dałeś gdzieś komentarz w tasku żeby nie zapomnieć

2019-05-24 15:01 UTC, xylini commented on src/main/java/pl/edu/agh/timekeeper/controller/AddRestrictionController.java
>              System.out.println("Restriction for this application already exists");
tutaj było:
// TODO: show message "Restriction with given name already exists"
i jest usunięte a nie widzę nigdzie taska żeby to zrobić, chyba że istnieje task w którym ma to być zrobione lub dałeś gdzieś komentarz w tasku żeby nie zapomnieć

2019-05-24 15:02 UTC, xylini commented on src/main/java/pl/edu/agh/timekeeper/controller/AddRestrictionController.java
>              System.out.println("Restriction for this application already exists");
A przy okazji to chyba nie ten task ale jak coś to gdy doda się taką samą appke to się wawala program z okno z dodawania zostaje

2019-05-26 20:26 UTC, closed without merging

2019-05-26 20:27 UTC, tadeq commented
CROC-43 zawiera zmiany z tego brancha